export const Buttons = [
    { name: 'C', type: 'init', isEvent: true },
    { name: '%', type: 'default', isEvent: false },
    { name: '()', type: 'default', isEvent: false },
    { name: '÷', type: 'operator', isEvent: true },
    { name: '7', type: 'default', isEvent: true },
    { name: '8', type: 'default', isEvent: true },
    { name: '9', type: 'default', isEvent: true },
    { name: '×', type: 'operator', isEvent: true },
    { name: '4', type: 'default', isEvent: true },
    { name: '5', type: 'default', isEvent: true },
    { name: '6', type: 'default', isEvent: true },
    { name: '-', type: 'operator', isEvent: true },
    { name: '1', type: 'default', isEvent: true },
    { name: '2', type: 'default', isEvent: true },
    { name: '3', type: 'default', isEvent: true },
    { name: '+', type: 'operator', isEvent: true },
    { name: '.', type: 'default', isEvent: false },
    { name: '0', type: 'default', isEvent: true },
    { name: null, type: 'delete', isEvent: true },
    { name: '=', type: 'equal', isEvent: true },
];
